#!/bin/bash

declare -a options=("
$HOME/.bar.sh
$HOME/.bashrc
$HOME/.gitignore
$HOME/.profile
$HOME/.config/alacritty/alacritty.yml
$HOME/.config/awesome/rc.lau
$HOME/.config/bpytop/bpytop.conf
$HOME/.config/broot/conf.toml
$HOME/.config/dmenufm/dmenufm.conf
$HOME/.config/dunst/dunstrc
$HOME/.config/fish/config.fish
$HOME/.config/picom/picom.conf
$HOME/.config/polybar/config
$HOME/.config/rofi/rofi.conf
$HOME/.config/starship.toml
$HOME/.screenlayout/default.sh
$HOME/.screenlayout/default.sh
$HOME/.SpaceVim.d/init.toml
---
/env/bin/m-edit-configs.sh
/env/bin/m-quick-cmd.sh
---
$HOME/Documents/.todo
$HOME/Documents/.todo2
")

choice=$(echo -e "${options[@]}" | rofi -dmenu -g 2 -l 15 -i -p 'Edit File: ')

exec alacritty -e vim $choice


