#!/bin/bash
# Orginally from Derek Taylor http://www.gitlab.com/dwt1/
# Visit http://www.youtube.com/c/DistroTube
# 
# Dmenu/Rofi script for launching system monitoring programs.


declare -a options=("bashtop
bpytop
glances
gtop
htop
iftopp
iotop
iptraf-ng
nmon
s-tui
ncspot
ncdu
stacer
homemon
quit")

choice=$(echo -e "${options[@]}" | rofi -dmenu -g 2 -l 8 -i -p 'Monitors: ')

case $choice in
	quit)
		echo "Program terminated." && exit 1
	;;
	bashtop| \
	bpytop| \
	glances| \
	gtop| \
	htop| \
	nmon| \
	ncdu| \
	ncspot| \
	s-tui)
        exec alacritty -e $choice
	;;
	iftop| \
	iotop| \
	stacer| \
	iptraf-ng)
        exec alacritty -e gksu $choice
	;;
	homemon)
        exec homemon
	;;
	*)
		exit 1
	;;
esac

