#!/bin/bash
# Orginally from Derek Taylor http://www.gitlab.com/dwt1/
# Visit http://www.youtube.com/c/DistroTube
# 
# Dmenu/Rofi script for managing a todo list

file="$HOME/Documents/.todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a Item: "

$(sort -o "$file" "$file")
cmd=$(rofi -dmenu -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi
 
  $(sort -o "$file" "$file")
	cmd=$(rofi -dmenu -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
