#!/bin/bash

IMG_PATH=/env/screenshots
FILENAME="${IMG_PATH}/%Y%m%d-%s.png"

case $1 in

  select)
    scrot -d 1 --select --line style=dash,width=2,color="red" "${FILENAME}"
    notify-send -u low 'Scrot' 'Selection taken and saved'
    ;;
  focused)
    scrot -d 1 --focused "${FILENAME}"
    notify-send -u low 'Scrot' 'Focused Window Screenshot saved'
    ;;
  *)
   scrot -d 1 "${FILENAME}"
   notify-send -u low 'Scrot' 'Fullscreen taken and saved'
   ;;

esac