#!/bin/bash
artist_elipsis=
title_elipsis=
a_len=15
t_len=20

artist=$(playerctl metadata xesam:artist)
title=$(playerctl metadata xesam:title)
if [ ${#artist} -gt $a_len ]; then artist_elipsis="..."; fi
if [ ${#title} -gt $t_len ]; then title_elipsis="..."; fi

echo "${artist:0:a_len}${artist_elipsis}-${title:0:t_len}${title_elipsis}"

